USE beer

# Partie 1

SELECT `ANNEE`, `NUMERO_TICKET`, `DATE_VENTE` 
FROM ticket 
WHERE `DATE_VENTE` = '2014-01-15'

SELECT `ANNEE`, `NUMERO_TICKET`, `DATE_VENTE` 
FROM ticket 
WHERE DATE_VENTE BETWEEN '2014-01-15' AND '2014-01-17'

SELECT `ANNEE`, `NUMERO_TICKET`, `DATE_VENTE` 
FROM ticket 
WHERE DATE_VENTE 
BETWEEN '2014-03-01' AND '2014-03-31'

SELECT `ANNEE`, `NUMERO_TICKET`, `DATE_VENTE` 
FROM ticket 
WHERE DATE_VENTE 
BETWEEN '2014-03-01' AND '2014-04-30'

SELECT `ID_ARTICLE`, `NUMERO_TICKET`, `QUANTITE` 
FROM ventes
WHERE `QUANTITE` >= 50

SELECT `NUMERO_TICKET` 
FROM ventes
WHERE `ID_ARTICLE` = 500

SELECT `ID_ARTICLE`, `NOM_ARTICLE`, `ID_Couleur`
FROM article
WHERE `ID_Couleur` IS NOT NULL
ORDER BY `ID_Couleur` ASC LIMIT 1000

SELECT `ID_ARTICLE`, `NOM_ARTICLE`, `ID_Couleur`
FROM article
WHERE `ID_Couleur` IS NULL

SELECT `ANNEE`, `NUMERO_TICKET`, `DATE_VENTE`
FROM ticket
WHERE `DATE_VENTE` 
BETWEEN '2014-03-01' AND '2014-03-31' 
OR `DATE_VENTE` BETWEEN '2014-06-01' AND '2014-06-30'

# Partie 2

SELECT `NUMERO_TICKET`, SUM(`QUANTITE`) AS `qteTotal`
FROM ventes
GROUP BY `NUMERO_TICKET`
ORDER BY `qteTotal` DESC

SELECT `NUMERO_TICKET`, SUM(`QUANTITE`) AS `qteTotal`
FROM ventes
GROUP BY `NUMERO_TICKET`
HAVING `qteTotal` > 500
ORDER BY `qteTotal` DESC

SELECT `NUMERO_TICKET`, SUM(`QUANTITE`) AS `qteTotal`
FROM ventes
WHERE `QUANTITE` < 50
GROUP BY `NUMERO_TICKET`
HAVING `qteTotal` > 500
ORDER BY `qteTotal` DESC









